trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: "renovatebot"

steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: .npmrc
  - bash: |
      git config --global user.email 'bot@renovateapp.com'
      git config --global user.name 'Renovate Bot'
      npm exec --userconfig .npmrc renovate      
    env:
      TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(githubtoken)