trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: "renovatebot"

steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: .npmrc
  - bash: |
      cat /home/vsts/work/1/s/.npmrc
      git config --global user.email 'bot@renovateapp.com'
      git config --global user.name 'Renovate Bot'
      npm login ajitddarade betfqjfzf5vk6sstksu3q745v4kep4txktm6frx2eaavfwefteva pkgs.dev.azure.com/snyk-demo123/Main/_packaging/SecurityTesting/npm/registry
      npm exec --userconfig .npmrc renovate      
    env:
      TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(githubtoken)